# Generated by Django 4.2.2 on 2023-10-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcreation',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
