# Generated by Django 4.2.2 on 2023-10-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_bankcreation_balance_transactions_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='name',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
