# Generated by Django 4.2.2 on 2023-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_transactions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcreation',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
