# Generated by Django 4.2.2 on 2023-10-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_alter_bankcreation_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcreation',
            name='opn_bal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
